/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Angelo PC
 */
public class AdministradorView extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorView
     */
    public AdministradorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarAgente = new javax.swing.JButton();
        cosultarCliente = new javax.swing.JButton();
        registrarAgente = new javax.swing.JButton();
        CerrarSesionButton = new javax.swing.JButton();
        loginbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultarAgente.setBackground(new java.awt.Color(178, 60, 58));
        consultarAgente.setForeground(new java.awt.Color(255, 255, 255));
        consultarAgente.setText("Consultar");
        consultarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAgenteActionPerformed(evt);
            }
        });
        getContentPane().add(consultarAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 333, 80, 40));

        cosultarCliente.setBackground(new java.awt.Color(178, 60, 58));
        cosultarCliente.setForeground(new java.awt.Color(255, 255, 255));
        cosultarCliente.setText("Consultar");
        cosultarCliente.setActionCommand("ConsultarClientes");
        cosultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosultarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cosultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 453, 80, 40));

        registrarAgente.setBackground(new java.awt.Color(178, 60, 58));
        registrarAgente.setForeground(new java.awt.Color(255, 255, 255));
        registrarAgente.setText("Registrar");
        registrarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAgenteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 213, 80, 40));

        CerrarSesionButton.setBackground(new java.awt.Color(255, 255, 255));
        CerrarSesionButton.setText("Cerrar Sesión");
        getContentPane().add(CerrarSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        loginbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AdministratorBG.png"))); // NOI18N
        getContentPane().add(loginbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAgenteActionPerformed
            this.setVisible(false);
            RegistrarNuevoAgenteView reg = new RegistrarNuevoAgenteView();
            reg.setVisible(true);
    }//GEN-LAST:event_registrarAgenteActionPerformed

    private void consultarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAgenteActionPerformed
        this.setVisible(false);
        ConsultaAgentesView ca = new ConsultaAgentesView();
        ca.setVisible(true);
    }//GEN-LAST:event_consultarAgenteActionPerformed

    private void cosultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosultarClienteActionPerformed
        this.setVisible(false);
        ConsultaClientesView ca = new ConsultaClientesView();
        ca.setVisible(true);
    }//GEN-LAST:event_cosultarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesionButton;
    private javax.swing.JButton consultarAgente;
    private javax.swing.JButton cosultarCliente;
    private javax.swing.JLabel loginbg;
    private javax.swing.JButton registrarAgente;
    // End of variables declaration//GEN-END:variables
}
